## 1. PERKALIAN


In [9]:
A = np.array([[26, 8, 5]])
B = np.array([[15, 80, 37]])

perkalian = A * B
print (perkalian)

[[390 640 185]]


## 2. PENGURANGAN

In [10]:
A = np.array([[26, 8, 5]])
B = np.array([[15, 80, 37]])

pengurangan = A - B
print (pengurangan)

[[ 11 -72 -32]]


## 3. TRANSPOSE


In [20]:
import numpy as np

A = np.array([[26, 8, 5], [15, 80, 37]])

transpose_A = np.transpose(A)

print(transpose_A)

[[26 15]
 [ 8 80]
 [ 5 37]]


## 4. INVERSE


In [7]:
import numpy as np

A = np.array([[26, 85], [80,37]])

inverse_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print(inverse_A)


invers matriks A:
[[-0.00633779  0.01455978]
 [ 0.01370332 -0.00445358]]


## 5. DETERMINANT

In [9]:
import numpy as np

A = np.array([[26, 85], [80,37]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: -5837.999999999996
